# Generated by Django 5.1.5 on 2025-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del País')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioBautismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.PositiveIntegerField()),
                ('folio', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_bautismo', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('nombreB', models.CharField(max_length=50)),
                ('apellidosB', models.CharField(max_length=50)),
                ('nombre_padre', models.CharField(max_length=50)),
                ('nombre_madre', models.CharField(max_length=50)),
                ('nombre_abuelo_paterno', models.CharField(max_length=50)),
                ('nombre_abuela_paterna', models.CharField(max_length=50)),
                ('nombre_abuelo_materno', models.CharField(max_length=50)),
                ('nombre_abuela_materna', models.CharField(max_length=50)),
                ('nombre_padrino', models.CharField(max_length=50)),
                ('nombre_madrina', models.CharField(max_length=50)),
                ('doy_fe', models.CharField(max_length=50)),
                ('tipo_hijo', models.CharField(choices=[('legit', 'Legitimo'), ('adoptv', 'Adoptivo'), ('ilegit', 'Ilegítimo')], max_length=15)),
            ],
        ),
    ]
