# Generated by Django 5.1.5 on 2025-01-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='nombre',
            new_name='nombre_Pais',
        ),
    ]
