# Generated by Django 5.1.5 on 2025-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bautismos', '0002_rename_nombre_pais_nombre_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=16)),
            ],
        ),
    ]
